for _, m in ipairs({
    "filetype",
    "remaps",
    "visual-move",
    "netrw",
    "tab",
    "term",
    "cursor-jump",
    "comments",
    "indent",
    "spell",
    "func-telescope",
    "cmd",
    "tab-completion",
    "latex",
    "eof",
    "quickfix",
    "grep",
    "man",
    "split-max",
    "buffer",
    "build",
}) do
    require("user." .. m)
end
